## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import sys

def build(bld):
    obj = bld.create_ns3_program('simulator-main', ['node'])
#    obj.env.append_value('LINKFLAGS','-lcrypto')
    obj.source = [ 
        'simulator-main.cc',
        'ls-routing-protocol/ls-routing-protocol.cc',
        'ls-routing-protocol/ls-message.cc',
        'ls-routing-protocol/ls-routing-helper.cc',
        'dv-routing-protocol/dv-routing-protocol.cc',
        'dv-routing-protocol/dv-message.cc',
        'dv-routing-protocol/dv-routing-helper.cc',
        'gu-search/gu-search.cc',
        'gu-search/gu-chord.cc',
        'gu-search/gu-chord-message.cc',
        'gu-search/gu-search-message.cc',
        'gu-search/gu-search-helper.cc',
        'common/ping-request.cc',
        'common/gu-log.cc',
        'common/gu-routing-protocol.cc',
        'common/gu-application.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'cosc525'
    headers.source = [
      'ls-routing-protocol/ls-routing-protocol.h',
      'ls-routing-protocol/ls-routing-helper.h',
      'ls-routing-protocol/ls-message.h',
      'dv-routing-protocol/dv-routing-protocol.h',
      'dv-routing-protocol/dv-routing-helper.h',
      'dv-routing-protocol/dv-message.h',
      'gu-search/gu-search.h',
      'gu-search/gu-chord.h',
      'gu-search/gu-chord-message.h',
      'gu-search/gu-search-message.h',
      'gu-search/gu-search-helper.h',
      'common/gu-log.h',
      'common/ping-request.h',
      'common/gu-routing-protocol.h',
      'common/gu-application.h',
      ]
